# Generated by Django 6.0.1 on 2026-02-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_affect', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('measure', models.CharField(max_length=15)),
                ('influence_on_other', models.ManyToManyField(related_name='influence_on_me', through='app.ParameterRelations', to='app.parameters')),
            ],
        ),
        migrations.AddField(
            model_name='parameterrelations',
            name='from_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_links', to='app.parameters'),
        ),
        migrations.AddField(
            model_name='parameterrelations',
            name='to_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='app.parameters'),
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_root', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.subsystem')),
            ],
        ),
        migrations.AddField(
            model_name='parameters',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='app.subsystem'),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('subsystem', 'number')},
        ),
    ]
