# Generated by Django 6.0.1 on 2026-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='is_goal',
            field=models.BooleanField(default=False),
        ),
    ]
