# Generated by Django 5.2.7 on 2026-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='measure',
            field=models.CharField(choices=[('В', 'Вольты')], default='В', max_length=5),
        ),
    ]
