# Generated by Django 6.0.1 on 2026-01-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parameters_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterrelations',
            name='is_affect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameterrelations',
            name='from_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_links', to='app.parameters'),
        ),
        migrations.AlterField(
            model_name='parameterrelations',
            name='to_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='app.parameters'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='measure',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='app.subsystem'),
        ),
    ]
