# Generated by Django 6.0.1 on 2026-04-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parameters_is_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='description',
            field=models.TextField(blank=True, help_text='Описание параметра', null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='measure',
            field=models.CharField(help_text='Единица измерения', max_length=15),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(help_text='Название параметра', max_length=20),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='number',
            field=models.IntegerField(help_text='Порядковый номер параметра'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='subsystem',
            field=models.ForeignKey(blank=True, help_text='Подсистема, к которой относится параметр', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='app.subsystem'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='description',
            field=models.TextField(blank=True, help_text='Описание назначения подсистемы', null=True),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='is_root',
            field=models.BooleanField(default=True, help_text='Является ли корневой подсистемой'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='name',
            field=models.CharField(help_text='Название подсистемы', max_length=200),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='number',
            field=models.IntegerField(help_text='Порядковый номер подсистемы'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительская подсистема (если есть)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.subsystem'),
        ),
    ]
