# Generated by Django 6.0.1 on 2026-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parameterrelations_is_affect_subsystem_is_root_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
