# Generated by Django 6.0.1 on 2026-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parameters_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(help_text='Название параметра', max_length=50),
        ),
    ]
