# Generated by Django 6.0.1 on 2026-05-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_parameters_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('subsystem', 'number', 'name')},
        ),
        migrations.CreateModel(
            name='ParameterImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Кто влияет')),
                ('first_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_parameter', to='app.parameters')),
                ('second_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_parameter', to='app.parameters')),
            ],
        ),
    ]
