# Generated by Django 6.0.1 on 2026-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_parameters_unique_together_parameterimportance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterimportance',
            name='value',
            field=models.IntegerField(default=0, help_text='Кто влияет'),
        ),
    ]
