# Generated by Django 5.2.7 on 2026-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_finalize_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='number',
            field=models.IntegerField(blank=True, help_text='Порядковый номер параметра (назначается автоматически)'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='number',
            field=models.IntegerField(blank=True, help_text='Порядковый номер подсистемы (назначается автоматически)'),
        ),
    ]
